-- MySQL Script generated by MySQL Workbench
-- Tue May 26 12:22:13 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Direcciones` (
  `id_direccion` INT NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(50) NOT NULL,
  `region` VARCHAR(30) NOT NULL,
  `comuna` VARCHAR(40) NOT NULL,
  `calle` VARCHAR(50) NOT NULL,
  `numero_casa` VARCHAR(10) NOT NULL,
  `numero_apartamento` VARCHAR(5) NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id_direccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipos_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipos_usuario` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(20) NOT NULL,
  `descripcion_tipo` VARCHAR(200) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id_tipo_usuario`),
  UNIQUE INDEX `nombre_tipo_UNIQUE` (`nombre_tipo` ASC) VISIBLE,
  UNIQUE INDEX `descripcion_tipo_UNIQUE` (`descripcion_tipo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_usuario` INT NOT NULL,
  `id_direccion` INT NOT NULL,
  `nombre_cliente` VARCHAR(40) NOT NULL,
  `saldo_pendiente` INT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_Clientes_Direcciones_idx` (`id_direccion` ASC) VISIBLE,
  INDEX `fk_Clientes_tipos_usuario1_idx` (`id_tipo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Clientes_Direcciones`
    FOREIGN KEY (`id_direccion`)
    REFERENCES `mydb`.`Direcciones` (`id_direccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clientes_tipos_usuario1`
    FOREIGN KEY (`id_tipo_usuario`)
    REFERENCES `mydb`.`tipos_usuario` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(100) NOT NULL,
  `stock_producto` INT NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ventas` (
  `id_venta` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad_productos` INT NOT NULL,
  `precio_total` DECIMAL(10,2) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id_venta`),
  INDEX `fk_Ventas_Clientes1_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_Ventas_Productos1_idx` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `fk_Ventas_Clientes1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`Clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Productos1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`Productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Insertar datos
INSERT INTO Direcciones(pais, region, comuna, calle, numero_casa, created_by)
VALUES("Chile", "Región Metropolitana", "San Ramón", "Llo Lleó", "1948", 1),
("Chile", "Región Metropolitana", "San Ramón", "Doñihue", "2945", 1),
("Chile", "Región Metropolitana", "San Ramón", "Américo Vespucio", "2775", 1);

INSERT INTO tipos_usuario(nombre_tipo, descripcion_tipo, created_by)
VALUES("Administrador", "Acceso total", 1),
("Usuario", "Funciones básicas del sitio", 1);

INSERT INTO Clientes(id_tipo_usuario, id_direccion, nombre_cliente, saldo_pendiente, created_by)
VALUES(1, 1, "Donovan", 0, 1),
(2, 2, "MatildeX", 0, 1),
(2, 3, "Randy", 0, 1),
(2, 2, "Martín", 900, 1);

INSERT INTO Productos(nombre_producto, stock_producto, precio_unitario, created_by)
VALUES("Laptop", 10, 199.99, 1),
("Mouse", 5, 15.99, 1),
("Disco sólido externo 2tb", 100, 229.99, 1),
("Disket", 22, 12.5, 1);

INSERT INTO Ventas(id_cliente, id_producto, cantidad_productos, precio_total, created_by)
VALUES(1, 1, 5, 999.95, 1),
(2, 2, 3, 47.97, 1),
(3, 3, 50, 1499.5, 1);

-- Borrar algunos datos
UPDATE Productos
SET deleted = 1
WHERE id_producto = 4;

UPDATE Clientes
SET deleted = 1
WHERE id_cliente = 4;

-- Mostrar clientes activos
SELECT id_cliente, nombre_cliente
FROM Clientes
WHERE deleted = 0;

-- Mostrar productos activos
SELECT id_producto, nombre_producto, stock_producto
FROM Productos
WHERE deleted = 0;