-- MySQL Script generated by MySQL Workbench
-- Tue May 19 12:14:38 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema_mensajes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_mensajes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_mensajes` DEFAULT CHARACTER SET utf8 ;
USE `sistema_mensajes` ;

-- -----------------------------------------------------
-- Table `sistema_mensajes`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`roles` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `nombreRol` VARCHAR(50) NOT NULL,
  `descripcionRol` VARCHAR(300) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP, -- CURRENT_TIMESTAMP: hora y fecha actual
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0, -- Borrado lógico: no se borra el elemento físicamente
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;

/* 
DIEGO MUERE- DEBEMOS SACARLO DEL SISTEMA. Borrado físico: DELETE FROM USUARIO
El borrado físico el dato deja de existir, no se puede recuperar
Borrado lógico: campo deleted activo - deleted 1
Podemos ocultar el dato para que el cliente no lo vea
pero no sale del sistema.
*/

-- -----------------------------------------------------
-- Table `sistema_mensajes`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `idRol` INT NOT NULL,
  `nombre_usuario` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password_hash` VARCHAR(100) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `username_UNIQUE` (`nombre_usuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_usuarios_tiposUsuario_idx` (`idRol` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_tiposUsuario`
    FOREIGN KEY (`idRol`)
    REFERENCES `sistema_mensajes`.`roles` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_mensajes`.`mensajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`mensajes` (
  `idMensaje` INT NOT NULL AUTO_INCREMENT,
  `receptor` INT NOT NULL,
  `emisor` INT NOT NULL,
  `contenido` TEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`idMensaje`),
  INDEX `fk_mensajes_usuarios1_idx` (`emisor` ASC) VISIBLE,
  INDEX `fk_mensajes_usuarios2_idx` (`receptor` ASC) VISIBLE,
  CONSTRAINT `fk_mensajes_usuarios1`
    FOREIGN KEY (`emisor`)
    REFERENCES `sistema_mensajes`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensajes_usuarios2`
    FOREIGN KEY (`receptor`)
    REFERENCES `sistema_mensajes`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_mensajes`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_mensajes`.`comentarios` (
  `idComentario` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `contenido` TEXT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`idComentario`),
  INDEX `fk_comentarios_usuarios1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_usuarios1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `sistema_mensajes`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Insertar datos en tablas
USE sistema_mensajes;

-- Insertar datos a la tabla de roles
INSERT INTO roles(nombreRol, descripcionRol, created_by)
VALUES ("Administrador", "Acceso total", 1),
("Premium", "Acceso especial.", 1),
("Usuario", "Acceso limitado.", 1),
("Sancionado", "Solo vista.", 1),
("Vetado", "No puede acceder al sitio.", 1);

-- Insertar datos a la tabla de usuarios
INSERT INTO usuarios(idRol, nombre_usuario, email, password_hash)
VALUES (1, "Patricia", "patricia@codingdojo.com", "ih82/(hjSAO22-186nd"),
(2, "Andrea", "andrea@codingdojo.com", "iuA8(!($hdHkas_s"),
(3, "Katya", "katya@codingdojo.com", "ASHFJ)#(kdÑ_d,"),
(4, "Matías", "matias@gmail.com", "SKFJ-_S)_(!)%"),
(5, "Fresia", "fresia@comeduc.cl", "AKAISFU)(#__fg");

-- Insertar datos a la tabla de mensajes
INSERT INTO mensajes(receptor, created_by, emisor, contenido)
VALUES (1, 2, 2, "Hola amiga cómo estás"),
(2, 3, 3, "Me caes muy bien amiga jaja"),
(3, 4, 4, "Eres nueva por lo que veo"),
(4, 5, 5, "No te conozco, creo que no eres de acá"),
(5, 1, 1, "Espero estés bien por hoy");

-- Insertar datos a la tabla de comentarios
INSERT INTO comentarios(idUsuario, contenido, created_by)
VALUES (1, "Muy buena amiga", 2),
(2, "No sé qué pensar", 3),
(3, "Tal vez tenga una oportuniodad", 4),
(4, "Chico raro", 5),
(5, "Por qué son así", 1);

-- CONSULTAS SIMPLES CON CONDICIÓN
-- WHERE en MySQL: Mostrar mensajes donde el remitente sea Matías
SELECT contenido, emisor
FROM mensajes
WHERE emisor = 4; -- WHERE aplica condición sobre consulta

-- MOSTRAR USUARIOS QUE ESTÁN ACTIVOS (DELETE = 0)
SELECT nombre_usuario, email, idRol
FROM usuarios
WHERE deleted = 0;

-- BORRAR USUARIO LÓGICAMENTE
UPDATE usuarios
SET deleted = 1
WHERE idUsuario = 1;

-- MOSTRAR USUARIOS QUE ESTÁN ELIMINADOS (DELETE = 1)
SELECT nombre_usuario, email, idRol
FROM usuarios
WHERE deleted = 1;

-- RECUPERAR USUARIO
UPDATE usuarios
SET deleted = 0
WHERE idUsuario = 1;

-- MOSTRAR USUARIOS QUE ESTÁN ACTIVOS (DELETE = 0)
SELECT nombre_usuario, email, idRol
FROM usuarios
WHERE deleted = 0;

-- BORRAR USUARIO LÓGICAMENTE
UPDATE usuarios
SET deleted = 1
WHERE idUsuario = 2;

-- MOSTRAR USUARIOS QUE ESTÁN ELIMINADOS (DELETE = 1)
SELECT nombre_usuario, email, idRol
FROM usuarios
WHERE deleted = 1;

-- MOSTRAR USUARIOS QUE ESTÁN ACTIVOS (DELETE = 0)
SELECT nombre_usuario, email, idRol
FROM usuarios
WHERE deleted = 0;