-- MySQL Script generated by MySQL Workbench
-- Tue Jun  2 08:10:59 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Database Filmoteca
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `Filmoteca` DEFAULT CHARACTER SET utf8;
USE `Filmoteca`;

-- -----------------------------------------------------
-- Table `Filmoteca`.`Tipos_de_formatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Filmoteca`.`Tipos_de_formatos` (
  `id_tipo_formato` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo_formato` VARCHAR(50) NOT NULL,
  `descripcion_tipo_formato` VARCHAR(100) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id_tipo_formato`),
  UNIQUE INDEX `nombre_tipo_formato_UNIQUE` (`nombre_tipo_formato` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Filmoteca`.`Formatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Filmoteca`.`Formatos` (
  `id_formato` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_formato` INT NOT NULL,
  `nombre_formato` VARCHAR(15) NOT NULL,
  `descripcion_formato` VARCHAR(150) NOT NULL,
  `capacidad_KB` INT NOT NULL,
  `resolucion_X` INT NOT NULL,
  `resolucion_Y` INT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id_formato`),
  UNIQUE INDEX `nombre_formato_UNIQUE` (`nombre_formato` ASC) VISIBLE,
  INDEX `fk_Formatos_Tipos_de_formatos_idx` (`id_tipo_formato` ASC) VISIBLE,
  CONSTRAINT `fk_Formatos_Tipos_de_formatos`
    FOREIGN KEY (`id_tipo_formato`)
    REFERENCES `Filmoteca`.`Tipos_de_formatos` (`id_tipo_formato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Filmoteca`.`Películas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Filmoteca`.`Películas` (
  `id_pelicula` INT NOT NULL AUTO_INCREMENT,
  `id_formato` INT NOT NULL,
  `titulo_pelicula` VARCHAR(200) NOT NULL,
  `anio_publicacion` DATE NOT NULL,
  `restaurado` TINYINT(1) NOT NULL,
  `precio_unitario` FLOAT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id_pelicula`),
  INDEX `fk_Películas_Formatos1_idx` (`id_formato` ASC) VISIBLE,
  CONSTRAINT `fk_Películas_Formatos1`
    FOREIGN KEY (`id_formato`)
    REFERENCES `Filmoteca`.`Formatos` (`id_formato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Filmoteca`.`Tipos_de_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Filmoteca`.`Tipos_de_usuario` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo_usuario` VARCHAR(50) NOT NULL,
  `descripcion_tipo_usuario` VARCHAR(100) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id_tipo_usuario`),
  UNIQUE INDEX `nombre_tipo_formato_UNIQUE` (`nombre_tipo_usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Filmoteca`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Filmoteca`.`Usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_usuario` INT NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `password_hash` VARCHAR(200) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Usuarios_Tipos_de_usuario1_idx` (`id_tipo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Tipos_de_usuario1`
    FOREIGN KEY (`id_tipo_usuario`)
    REFERENCES `Filmoteca`.`Tipos_de_usuario` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Filmoteca`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Filmoteca`.`pedidos` (
  `id_pedidos` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`id_pedidos`),
  INDEX `fk_pedidos_Usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_Usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `Filmoteca`.`Usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Filmoteca`.`detalles_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Filmoteca`.`detalles_pedidos` (
  `id_pedidos` INT NOT NULL,
  `id_pelicula` INT NOT NULL,
  `precio_total` FLOAT NOT NULL,
  PRIMARY KEY (`id_pedidos`, `id_pelicula`),
  INDEX `fk_pedidos_has_Películas_Películas1_idx` (`id_pelicula` ASC) VISIBLE,
  INDEX `fk_pedidos_has_Películas_pedidos1_idx` (`id_pedidos` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_has_Películas_pedidos1`
    FOREIGN KEY (`id_pedidos`)
    REFERENCES `Filmoteca`.`pedidos` (`id_pedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_Películas_Películas1`
    FOREIGN KEY (`id_pelicula`)
    REFERENCES `Filmoteca`.`Películas` (`id_pelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
